services:
  yaedumerchbot:
    image: ${DOCKERHUB_USERNAME}/yaedumerchbot:latest
    container_name: yaedumerchbot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TG_TOKEN=${TG_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///bot.db}
      - ADMIN_IDS=${ADMIN_IDS}
      - PAYMENT_TOKEN=${PAYMENT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-False}
    volumes:
      - bot_data:/app/data
      - ./logs:/app/logs
    # healthcheck убран, чтобы не требовать локального HTTP /health
    # если нужен, можно вернуть любой простой проверкой процесса

volumes:
  bot_data:
    driver: local
