services:
  yaedumerchbot-preview:
    image: ${DOCKERHUB_USERNAME}/yaedumerchbot:pr-${PR_NUM}-latest
    container_name: yaedumerchbot-pr-${PR_NUM}
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///bot_pr_${PR_NUM}.db}
      - ADMIN_IDS=${ADMIN_IDS}
      - PAYMENT_TOKEN=${PAYMENT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - DEBUG=True
    volumes:
      - bot_data_pr_${PR_NUM}:/app/data
      - ./logs:/app/logs
    # без healthcheck и без портов — long polling

volumes:
  bot_data_pr_${PR_NUM}:
    driver: local
