name: YaEduMerchBot PR Preview Cleanup

on:
  pull_request:
    branches: ["main"]
    types: [closed]

permissions:
  contents: read

jobs:
  delete-preview:
    runs-on: [self-hosted, Windows, X64, yaedumerchbot]
    timeout-minutes: 15
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set env
        shell: powershell
        run: |
          $u='${{ secrets.DOCKERHUB_USERNAME }}'.ToLower()
          "IMAGE=$u/yaedumerchbot" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "PR_NUM=${{ github.event.pull_request.number }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Down preview stack
        shell: powershell
        env:
          BOT_TOKEN: ${{ env.BOT_TOKEN }}
        continue-on-error: true
        run: |
          echo "::add-mask::${env:BOT_TOKEN}"
          if (Test-Path 'compose.preview.yml') {
            docker compose -f compose.preview.yml -p yaedumerchbot_pr_$env:PR_NUM down -v
          }

      - name: Fallback remove container (if any)
        shell: powershell
        continue-on-error: true
        run: |
          docker rm -f yaedumerchbot-pr-$env:PR_NUM

      - name: Remove PR images (optional)
        shell: powershell
        continue-on-error: true
        run: |
          docker image rm "$($env:IMAGE):pr-$($env:PR_NUM)-latest"
          docker image prune -f
